
# tap repositories and their packages

tap 'homebrew/core'
brew 'aom'
brew 'apr'
brew 'apr-util'
brew 'argon2'
brew 'aspell'
brew 'autoconf'
brew 'awscli'
brew 'brotli'
brew 'ca-certificates'
brew 'cffi'
brew 'composer'
brew 'cryptography'
brew 'curl'
brew 'dav1d'
brew 'devspace'
brew 'docker'
brew 'docker-completion'
brew 'fnm'
brew 'fontconfig'
brew 'freetds'
brew 'freetype'
brew 'gd'
brew 'gettext'
brew 'giflib'
brew 'git'
brew 'gmp'
brew 'helm'
brew 'highway'
brew 'icu4c@77'
brew 'icu4c@78'
brew 'imath'
brew 'jpeg-turbo'
brew 'jpeg-xl'
brew 'krb5'
brew 'kubernetes-cli'
brew 'libavif'
brew 'libdeflate'
brew 'libnghttp2'
brew 'libnghttp3'
brew 'libngtcp2'
brew 'libpng'
brew 'libpq'
brew 'libsodium'
brew 'libssh2'
brew 'libtiff'
brew 'libtool'
brew 'libunistring'
brew 'libvmaf'
brew 'libzip'
brew 'little-cms2'
brew 'lz4'
brew 'm4'
brew 'mas'
brew 'mpdecimal'
brew 'net-snmp'
brew 'oniguruma'
brew 'openexr'
brew 'openjph'
brew 'openldap'
brew 'openssl@1.1'
brew 'openssl@3'
brew 'pcre2'
brew 'php'
brew 'pnpm'
brew 'pycparser'
brew 'python@3.13'
brew 'python@3.14'
brew 'readline'
brew 'rtmpdump'
brew 'spaceship'
brew 'sqlite'
brew 'thefuck'
brew 'tidy-html5'
brew 'unixodbc'
brew 'webp'
brew 'xz'
brew 'z'
brew 'zsh-async'
brew 'zstd'

tap 'homebrew/cask'
cask '1password'
cask 'appcleaner'
cask 'bruno'
cask 'font-fira-code'
cask 'github'
cask 'imageoptim'
cask 'iterm2'
cask 'mockoon'
cask 'openlens'
cask 'rectangle'
cask 'visual-studio-code'
cask 'vlc'

tap 'hashicorp/tap'
brew 'vault'

tap 'rcmdnk/file'
brew 'brew-file'

# App Store applications
mas '1Password 7 (7.9.11)', id: 1333542190
mas '1Password for Safari (8.11.18)', id: 1569813296
mas 'GarageBand (10.4.12)', id: 682658836
mas 'Hand Mirror (3.2)', id: 1502839586
mas 'iHosts (1.4.0)', id: 1102004240
mas 'iMovie (10.4.3)', id: 408981434
mas 'Keynote (14.4)', id: 409183694
mas 'Numbers (14.4)', id: 409203825
mas 'Pages (14.4)', id: 409201541
mas 'Sequel Ace (5.0.9)', id: 1518036000
